### ISSUE TITLE
Styling and scalability

### ISSUE THREAD

**Issue by sgfrank** [samuelcole/MarchBNB#10]
I'm a tech volunteer helping the Women's March with their digital tools. Vanessa Wurble head of Operations for the March and other national committee members have noticed your app and appreciate the work! Housing matching is a huge need right now as hotel prices are through the roof! For various liability reasons, they can't release their own application officially, so they're rooting for yours to catch on. I'm going to give you their style guide, you should consider using their branding (maybe not the logo though). https://docs.google.com/presentation/d/16j4rBmYAG1Zz3jC4MA3QZYoWv-WVePhp3coL16NgTmU/edit#slide=id.p

If you think your app can handle it, I'm going to reach out to various promoters about it. Your traffic may increase drastically, so let me know if you're ready.

Finally, I noticed some of your group wants to stay politically active through tech. Our organization, Blue Boost founded the day after the election to help progressive causes and campaigns with digital tools could use more talented devs. I'd like to extend an open invitation to any of your contributors. We also recommend progcode.co. We work closely with that network.

Keep up the good fight!

**Comment by samuelcole** [comment]
Cool! We lost contact with the March, so this project sort of stalled out. I'm happy to keep working on it with yall and support the traffic if it will be useful to you.

I'm personally interested in Blue Boost and progcode, can you email me at sam@samuelcole.name. I filled out the form at progcode...

**Comment by epferrari** [comment]
@sgfrank you mentioned not using the WMW logo. Does that still hold?
