### ISSUE TITLE
No Email Was Sent After I Created My Profile

### ISSUE THREAD

**Issue by cathycabrey** [samuelcole/MarchBNB#24]
And I checked my spam/junk file.  I want to sign up as a host.

**Comment by samuelcole** [comment]
oh weird, i see a bunch of delivered emails to an email that matches your github username

```
      "from": "admin@marchbnb.com",
      "subject": "MarchBNB - Confirm Your Email"
```

can you search for that subject line?

**Comment by cathycabrey** [comment]
to cathycabrey@me.com?

**Comment by cathycabrey** [comment]
I ended up logging in with my gmail account - which is not my primary account - just to see if it worked.  Which it did.  But I would prefer to use my cathycabrey@me.com account, which is associated with my Facebook.  It's the "Login with Facebook" button that didn't work.

**Comment by samuelcole** [comment]
yup! my logs show that marchbnb sent around 8 emails to that address... very strange that they aren't showing up...

**Comment by cathycabrey** [comment]
The one that you just sent me showed up in my @me.com inbox just now.

**Comment by samuelcole** [comment]
sorry about that, i guess it's just slow

**Comment by cathycabrey** [comment]
If you could change my hosting account to this address I would really appreciate it.  This is the account I check regularly - and I wouldn’t want to miss someone’s request.

Cathy Cabrey
cathycabrey@me.com

**Comment by cathycabrey** [comment]
I successfully created a hosting account with my cathycabrey@gmail.com account - that's the one I'd like to change.

**Comment by samuelcole** [comment]
i've moved the hosting, please verify the @me.com account anyways though, thanks!

**Comment by cathycabrey** [comment]
I haven’t received a verification email to my cathycabrey@me.com <mailto:cathycabrey@me.com> address yet - just the email from samuaelcole/MarchBNB you sent starting with “yup! my logs show …”

Cathy Cabrey
cathycabrey@me.com

**Comment by samuelcole** [comment]
oh weird, if you aren't receiving the verification email, you probably won't receive the requests either.

sorry for all the hassle, i think you'll have to check your gmail account or set it up to forward to your @me.com account: https://www.lifewire.com/how-to-forward-gmail-email-using-filters-1171934
