### ISSUE TITLE
Google authenticaion not working

### ISSUE THREAD

**Issue by robmyre** [samuelcole/MarchBNB#3]
Google authentication is not working. Getting a 400 error.

![google_error](https://cloud.githubusercontent.com/assets/21959358/20682967/354b5f6e-b578-11e6-88aa-6512356114f2.jpg)

**Comment by jessepinho** [comment]
@samuelcole Do you know who owns the Google app? Should we just create a new one?

**Comment by samuelcole** [comment]
I own it, I thought I added you to it though... or somebody... looking

**Comment by jessepinho** [comment]
Works now!
