### ISSUE TITLE
Make new favicon

### ISSUE THREAD

**Issue by jessepinho** [samuelcole/MarchBNB#7]

**Comment by rschroed** [comment]
![favicon](https://cloud.githubusercontent.com/assets/12657/20691270/aac1984c-b584-11e6-9b06-7324c861e21e.png)
![favicon](https://cloud.githubusercontent.com/assets/12657/20691281/bc42b3bc-b584-11e6-9ef6-489c4b48ebed.png)

**Comment by rschroed** [comment]
either of these work?

**Comment by jessepinho** [comment]
These are great, thanks! I'll prob use the blue one, since it fits the rest of the color scheme more :)
